### ISSUE TITLE
Installing olimex package library in Arduino

### ISSUE THREAD

**Issue by rvegele** [OLIMEX/OLIMEXINO-85#1]
The following link seems to be dead:
https://raw.githubusercontent.com/OLIMEX/Arduino_configurations/master/AVR/package_olimex _avr_index.json

Getting an error in arduino ide

**Comment by newtob** [comment]
I concur, any ideas where it might be re-listed?

**Comment by hehopmajieh** [comment]
Link is ok, try with :
https://raw.githubusercontent.com/OLIMEX/Arduino_configurations/master/AVR/package_olimex_avr_index.json

На ср, 4.08.2021 г. в 10:38 ч. Ben ***@***.***> написа:

**Comment by newtob** [comment]
You'r a superstar, it works!!

Many thanks,
B
_______
Ben
